app.version=${project.version}

# Database hi?n ch?a ???c ??ng ??n (c?u hình t?m th?i)
db.url=jdbc:sqlserver://localhost:1433;databaseName=JapaneseAlphabetQuiz;encrypt=true;trustServerCertificate=true;
db.enabled=false
